name: Execute Notebook

on:
  push:
    branches:
      - main
  # またはスケジュール実行
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          pip install jupyter
          pip install pandas
          pip install yfinance
          pip install papermill
      
      - name: Execute Notebook
        run: |
          papermill --log-output GitHub_Test.ipynb output.ipynb
      # アーティファクトのアップロード
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fr-Artifact
          path: Artifact**
